/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventas;
import Activar.MenuPrincipal;
import config.Conexion;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jonathan
 */
public class RealizarVenta extends javax.swing.JFrame {

    Conexion con1= new Conexion();
    Connection conet;
    DefaultTableModel modelo1;
    DefaultTableModel modelo2;
    Statement st;
    ResultSet rs;
    
    double Venta;
    String Vent;
    double GananciaDia;
    
        
    public RealizarVenta() {
        
        initComponents();
        
        setLocationRelativeTo(null);
        
        consultarKilos();
        consultarPiezas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        txtCantidadDisp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAniadirProducto = new javax.swing.JButton();
        btnTerminarDia = new javax.swing.JButton();
        btnFinalizarVenta = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos "));

        jLabel1.setText("Nombre del producto ");

        txtNombre.setEditable(false);
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio del producto");

        txtPrecio.setEditable(false);
        txtPrecio.setEnabled(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de productos a comprar");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel5.setText("Id del producto");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        jLabel6.setText("Cantidad Disponible");

        jLabel7.setText("Tipo de Producto");

        txtProducto.setEditable(false);
        txtProducto.setEnabled(false);

        txtCantidadDisp.setEditable(false);
        txtCantidadDisp.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidadDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18))
        );

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel2.setText("Realizar venta ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        btnAniadirProducto.setText("Añadir Producto");
        btnAniadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirProductoActionPerformed(evt);
            }
        });

        btnTerminarDia.setText("Terminar dia ");
        btnTerminarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarDiaActionPerformed(evt);
            }
        });

        btnFinalizarVenta.setText("Finalizar Venta");
        btnFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVentaActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAniadirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(btnTerminarDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnAniadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnTerminarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos"));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad Disponible", "Precio", "Tipo de Producto"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);
        if (Tabla1.getColumnModel().getColumnCount() > 0) {
            Tabla1.getColumnModel().getColumn(0).setPreferredWidth(40);
            Tabla1.getColumnModel().getColumn(1).setPreferredWidth(60);
            Tabla1.getColumnModel().getColumn(2).setPreferredWidth(40);
            Tabla1.getColumnModel().getColumn(3).setPreferredWidth(40);
            Tabla1.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos Piezas"));

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad Disponible", "Precio", "Tipo de Producto"
            }
        ));
        Tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla2);
        if (Tabla2.getColumnModel().getColumnCount() > 0) {
            Tabla2.getColumnModel().getColumn(0).setPreferredWidth(40);
            Tabla2.getColumnModel().getColumn(1).setPreferredWidth(60);
            Tabla2.getColumnModel().getColumn(2).setPreferredWidth(40);
            Tabla2.getColumnModel().getColumn(3).setPreferredWidth(50);
            Tabla2.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed
    
    //          Botones
    
    private void btnAniadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirProductoActionPerformed
        
        String nombre = txtId.getText();
        String kilo="Ki";
        String iden = nombre.substring(0,2);
        
        if (Double.valueOf(txtCantidadDisp.getText()) < Double.valueOf(txtCantidad.getText())){
            
            JOptionPane.showMessageDialog(null, "El numero disponible es menor al requerido", "Error", HEIGHT);
            
        } else {
            
            if (!iden.equals(kilo)){
                
                productoSelecionadoPieza();
                Nuevo();
                consultarPiezas();
        } else {
                
                productoSelecionadoKilo();
                Nuevo();
                consultarKilos();
            }
            
        }
        
    }//GEN-LAST:event_btnAniadirProductoActionPerformed

    private void txtfinalizarVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinalizarVenta1ActionPerformed

    }//GEN-LAST:event_txtfinalizarVenta1ActionPerformed

    //          Mostrar en texfields datos de fila selecionada
    
    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        
        
        int fila = Tabla1.getSelectedRow();
        if (fila == -1){
            
            JOptionPane.showMessageDialog(null, "No se seleciono fila");
            
        } else {
            
            String id = (String) Tabla1.getValueAt(fila, 0);
            String nomPro = (String) Tabla1.getValueAt(fila, 1);
            float kilos = Integer.parseInt((String)Tabla1.getValueAt(fila,2) .toString());
            float precio = Integer.parseInt((String)Tabla1.getValueAt(fila,3) .toString());
            String tipoProducto = (String) Tabla1.getValueAt(fila, 4);
           
            
            txtId.setText(""+id);
            txtNombre.setText(""+nomPro);
            txtCantidadDisp.setText(""+kilos);
            txtPrecio.setText(""+precio);
            txtProducto.setText(""+tipoProducto);
            
        }
        
        Tabla1.clearSelection();
        
    }//GEN-LAST:event_Tabla1MouseClicked

    private void Tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla2MouseClicked
        
        
        int fila2 = Tabla2.getSelectedRow();
        if (fila2 == -1){
            
            JOptionPane.showMessageDialog(null, "No se seleciono fila");
            
        } else {
            
            String id = (String) Tabla2.getValueAt(fila2, 0);
            String nomPro = (String) Tabla2.getValueAt(fila2, 1);
            int piezas = Integer.parseInt((String)Tabla2.getValueAt(fila2,2) .toString());
            String precio = (String) Tabla2.getValueAt(fila2, 3);
            String tipoProducto = (String) Tabla2.getValueAt(fila2, 4);
            
            
            txtId.setText(""+id);
            txtNombre.setText(""+nomPro);
            txtCantidadDisp.setText(""+piezas);
            txtPrecio.setText(""+precio);
            txtProducto.setText(""+tipoProducto);
 
        }
        
        Tabla2.clearSelection();
    }//GEN-LAST:event_Tabla2MouseClicked

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnTerminarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarDiaActionPerformed
        almacenarVentaDia();
        JOptionPane.showMessageDialog(null, "Resumen de venta \n \n Ganancias del dia: $"+GananciaDia, "Dia Terminado", HEIGHT);
        
        GananciaDia=0;
                
    }//GEN-LAST:event_btnTerminarDiaActionPerformed
    /*
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtMenuActionPerformed
    *///            Botones 
    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
        totalPago();
        GananciaDia = GananciaDia+Venta;
        Venta = 0;
        //actualizarTablas();
        
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarVenta().setVisible(true);
            }
        });
    }
    
    //          Acciones logicas
    
    void productoSelecionadoKilo(){
        
        modificarKilos();
        calculos();
       
    }
    
    void productoSelecionadoPieza(){
        
        modificarPiezas();
        calculos();
        
    }
    
    //          Mostrar Tablas
    
    void consultarKilos(){
        
        String sql = "SELECT * FROM inventario.inventariokilos;";
        
        try {
            
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            
            Object[] datos = new Object[5];
            modelo1 = (DefaultTableModel) Tabla1.getModel();
            
            while (rs.next()){
                
                datos [0] = rs.getString("id");
                datos [1] = rs.getString("nombre_producto");
                datos [2] = rs.getInt("cantidad_disponible");
                datos [3] = rs.getInt("costo_kilo");
                datos [4] = rs.getString("tipo_producto");
                
                modelo1.addRow(datos);
             
            }
            
            Tabla1.setModel(modelo1);
            
        }catch (Exception e){
            
        }
    } //fin consultar
    
    void consultarPiezas(){
        
        String sql = "SELECT * FROM inventario.inventariopiezas;";
        
        try {
            
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            
            Object[] datos = new Object[5];
            modelo2 = (DefaultTableModel) Tabla2.getModel();
            
            while (rs.next()){
                
                datos [0] = rs.getString("id_producto");
                datos [1] = rs.getString("nombre_producto");
                datos [2] = rs.getInt("piezas_disponibles");
                datos [3] = rs.getString("precio");
                datos [4] = rs.getString("tipo_producto");
                
                modelo2.addRow(datos);
             
            }
            
            Tabla2.setModel(modelo2);
            
        }catch (Exception e){
            
        }
    } //fin consultar
    
    //          Actualizar Tablas
    
    void actualizarTablas(){
        
        for (int i = 0 ; i<= Tabla1.getRowCount() ; i++){
            modelo1.removeRow(i);
            i = i-1;
        }
    } //fin limpiar tabla
    
    void actualizarPieza(){
        for (int j = 0 ; j<= Tabla2.getRowCount() ; j++){
            modelo2.removeRow(j);
            j = j-1;
        }
    }
    
    //          Restar cantidad
    
    void modificarKilos(){
        
        String id = txtId.getText();
        String nomPro = txtNombre.getText();
        String cantidadDisp = txtCantidadDisp.getText();
        String precio = txtPrecio.getText();
        String tipoProducto = txtProducto.getText();
        String cantidadVe = txtCantidad.getText();
        
        double kilo;
        kilo = Double.valueOf(txtCantidadDisp.getText())-Double.valueOf(txtCantidad.getText());

        String kilos = String.valueOf(kilo);
        
        try {
            
            if (id.equals("") || nomPro.equals("") || kilos.equals("") || precio.equals("") || tipoProducto.equals("")){
                
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                
            
            } else {
                
                String sql = "UPDATE `inventario`.`inventariokilos` SET `id` = '" + id + "', `nombre_producto` = '" +nomPro + "', `cantidad_disponible` = '" + kilos + "', `costo_kilo` = '" + precio + "', `tipo_producto` = '" + tipoProducto + "' WHERE (`id` = '" + id + "');" ;
                //UPDATE `inventario`.`inventariokilos` SET `id` = '1', `nombre_producto` = 'Queso Crema', `cantidad_disponible` = '12', `costo_kilo` = '25', `tipo_producto` = 'Queso' WHERE (`id` = '1234');
                
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                
                JOptionPane.showMessageDialog(null, "Producto añadido");
                
                actualizarTablas();
                
            }
            
        } catch (Exception e){

        }//fin try catch
    } //fin modificar
    
    void modificarPiezas(){
        
        String id = txtId.getText();
        String nomPro = txtNombre.getText();
        String cantidadDisp = txtCantidadDisp.getText();
        String precio = txtPrecio.getText();
        String tipoProducto = txtProducto.getText();
        String cantidadVe = txtCantidad.getText();
        
        int pieza;
        pieza = Integer.valueOf(txtCantidadDisp.getText())-Integer.valueOf(txtCantidad.getText());
        String piezas = String.valueOf(pieza);
        
        
        
        try {
            
            if (id.equals("") || nomPro.equals("") || piezas.equals("") || precio.equals("") || tipoProducto.equals("")){
                
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
            
            } else {
                
                String sql = "UPDATE `inventario`.`inventariopiezas` SET `id_producto` = '" + id + "', `nombre_producto` = '" +nomPro + "', `piezas_disponibles` = '" + piezas + "', `precio` = '" + precio + "', `tipo_producto` = '" + tipoProducto + "' WHERE (`id_producto` = '" + id + "');" ;
                //UPDATE `inventario`.`inventariopiezas` SET `id_producto` = '324', `nombre_producto` = 'Principal', `piezas_disponibles` = '24', `precio` = '14', `tipo_producto` = 'Galleta' WHERE (`id_producto` = '1234');
                
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                
                JOptionPane.showMessageDialog(null, "Producto añadido");
                actualizarPieza();
                actualizarTablas();
            }
            
        } catch (Exception e){

        }//fin try catch
    } //fin modificar
    
    //          Operaciones de precio
    
    void calculos(){
        
        double producto =0;
        producto = Double.valueOf(txtCantidad.getText())* Double.valueOf(txtPrecio.getText());
        
        //calculos de venta
        Venta=Venta+producto;
        
    }
    
    void totalPago(){
        
        try{
            
            String Vent = String.valueOf(Venta);
            JOptionPane.showMessageDialog(null, "El total a pagar es: $"+Venta,"Total de Venta",HEIGHT);
            
        }catch(Exception e){
            
        }
    }
    
    void Nuevo (){
        
        txtId.setText("");
        txtNombre.setText("");
        txtCantidadDisp.setText("");
        txtPrecio.setText("");
        txtProducto.setText("");
        txtCantidad.setText("");
        
        txtId.requestFocus();
    } //fin Nuevo
    
    void almacenarVentaDia(){

        
        String dia = new SimpleDateFormat("dd").format(Calendar.getInstance().getTime());
        String mes = new SimpleDateFormat("MM").format(Calendar.getInstance().getTime());
        String anio = new SimpleDateFormat("yyyy").format(Calendar.getInstance().getTime());
        
        Random random = new Random();
        int cod = random.nextInt(100000 + 1) + 1;
        
        String id_venta= "Ve"+anio+mes+dia+cod+"";
        String fecha_venta = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
        String ganancia_dia = String.valueOf(GananciaDia);
        
        try {
            
            if (id_venta.equals("") || fecha_venta.equals("") || ganancia_dia.equals("")){
                
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                
            
            } else {
                
                String sql = "INSERT INTO `inventario`.`gananciadia` (`id_venta`, `fecha_venta`, `ganancia_dia`) VALUES ('" + id_venta + "', '" + fecha_venta + "', '" + ganancia_dia + "');";
                //INSERT INTO `inventario`.`gananciadia` (`id_venta`, `fecha_venta`, `ganancia_dia`) VALUES ('Ve20220410123213', '2022/04/10', '1244321');

                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                
                JOptionPane.showMessageDialog(null, "Dia terminado");

            }
            
        } catch (Exception e){

        }//fin try catch
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JButton btnAniadirProducto;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnTerminarDia;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadDisp;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
